# Supply Chain Data Set

## PART - 1 - Data Cleaning and Feature Engineering

Dataset Link -https://www.kaggle.com/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis

### Uploading & Reading data

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# read a csv file 
import pandas as pd
df= pd.read_csv('DataCoSupplyChainDataset.csv',header= 0,encoding='unicode_escape')

### Interpretating and understanding the data

In [3]:
df.shape

(180519, 53)

In [4]:
# Display the first 10 rows of the dataframe
df.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class

In [5]:
df.describe() #describe the data

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [6]:
df.dtypes #check data types of each column

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [7]:
# Identifying variables with object datatype
df.dtypes[df.dtypes == 'object']

Type                          object
Delivery Status               object
Category Name                 object
Customer City                 object
Customer Country              object
Customer Email                object
Customer Fname                object
Customer Lname                object
Customer Password             object
Customer Segment              object
Customer State                object
Customer Street               object
Department Name               object
Market                        object
Order City                    object
Order Country                 object
order date (DateOrders)       object
Order Region                  object
Order State                   object
Order Status                  object
Product Image                 object
Product Name                  object
shipping date (DateOrders)    object
Shipping Mode                 object
dtype: object

In [8]:
# typecasting "order date" and "shipping date" to category type

df['order date (DateOrders)'] = df['order date (DateOrders)'].astype('category')
df['shipping date (DateOrders)'] = df['shipping date (DateOrders)'].astype('category')
# checking
df[['order date (DateOrders)','shipping date (DateOrders)']].dtypes

order date (DateOrders)       category
shipping date (DateOrders)    category
dtype: object

In [9]:
# typecasting "Order Item Product Price " to int type
df['Order Item Product Price'] = df['Order Item Product Price'].astype('int64')
# checking
df[['Order Item Product Price']].dtypes

Order Item Product Price    int64
dtype: object

In [10]:
# Calculate total number of cells in dataframe
df.columns
df.index
print("Total number of columns are: ", len(df.columns))
print("Total number of rows are: ", len(df.index))
print("Total number of cells in dataframe: ", len(df.columns) * len(df.index))

Total number of columns are:  53
Total number of rows are:  180519
Total number of cells in dataframe:  9567507

In [11]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [12]:
Array1 = [ABC for ABC in df.columns if df[ABC].dtypes !='O']
print(Array1)
print(len(Array1))

['Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Late_delivery_risk', 'Category Id', 'Customer Id', 'Customer Zipcode', 'Department Id', 'Latitude', 'Longitude', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Price', 'Product Status', 'shipping date (DateOrders)']
31

In [13]:
# Count of numerical features 
numerical_features = [f for f in df.columns if df[f].dtypes!='O']
print('Count of Numerical Features :',len(numerical_features))

Count of Numerical Features : 31

In [14]:
# Count of Categorical features 
cat_features = [c for c in df.columns if df[c].dtypes=='O']
print('Count of Categorical Features :',len(cat_features))

Count of Categorical Features : 22

In [15]:
#find duplicates and return 0 if there aren't any duplicates
df.duplicated().sum()

0

In [16]:
df.shape

(180519, 53)

In [17]:
#Checking for null values
df.isnull().sum() #returns the number of missing values in the dataset.

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [18]:
#returns missing value in percentage form for easier interpretation

missing_values=df.isna().sum()

missing_values / len(df)

Type                             0.000000
Days for shipping (real)         0.000000
Days for shipment (scheduled)    0.000000
Benefit per order                0.000000
Sales per customer               0.000000
Delivery Status                  0.000000
Late_delivery_risk               0.000000
Category Id                      0.000000
Category Name                    0.000000
Customer City                    0.000000
Customer Country                 0.000000
Customer Email                   0.000000
Customer Fname                   0.000000
Customer Id                      0.000000
Customer Lname                   0.000044
Customer Password                0.000000
Customer Segment                 0.000000
Customer State                   0.000000
Customer Street                  0.000000
Customer Zipcode                 0.000017
Department Id                    0.000000
Department Name                  0.000000
Latitude                         0.000000
Longitude                        0.000000
Market                           0.000000
Order City                       0.000000
Order Country                    0.000000
Order Customer Id                0.000000
order date (DateOrders)          0.000000
Order Id                         0.000000
Order Item Cardprod Id           0.000000
Order Item Discount              0.000000
Order Item Discount Rate         0.000000
Order Item Id                    0.000000
Order Item Product Price         0.000000
Order Item Profit Ratio          0.000000
Order Item Quantity              0.000000
Sales                            0.000000
Order Item Total                 0.000000
Order Profit Per Order           0.000000
Order Region                     0.000000
Order State                      0.000000
Order Status                     0.000000
Order Zipcode                    0.862397
Product Card Id                  0.000000
Product Category Id              0.000000
Product Description              1.000000
Product Image                    0.000000
Product Name                     0.000000
Product Price                    0.000000
Product Status                   0.000000
shipping date (DateOrders)       0.000000
Shipping Mode                    0.000000
dtype: float64

### Value counts

In [19]:
#Return a Series containing counts of unique values
df['Type'].value_counts()

DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: Type, dtype: int64

In [20]:
df['Sales per customer'].value_counts()

122.839996    1264
109.190002    1247
124.790001    1243
129.990005    1243
116.989998    1243
              ...
455.950012       1
470.250000       1
424.790008       1
98.010002        1
474.760010       1
Name: Sales per customer, Length: 2927, dtype: int64

In [21]:
df['Delivery Status'].value_counts()

Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: Delivery Status, dtype: int64

In [22]:
df['Late_delivery_risk'].value_counts()

1    98977
0    81542
Name: Late_delivery_risk, dtype: int64

In [23]:
df['Category Id'].value_counts()

17    24551
18    22246
24    21035
46    19298
45    17325
48    15540
43    13729
9     12487
29    10984
37     2029
40     1780
36     1475
26     1201
13     1127
35     1070
41      974
75      838
63      652
76      650
3       632
7       614
62      592
74      529
33      524
72      492
66      484
68      484
67      483
64      442
32      441
44      440
71      434
65      431
12      423
59      405
38      384
69      362
73      357
5       343
6       328
11      309
30      283
61      271
70      208
60      207
31      181
2       138
10      111
16       68
4        67
34       61
Name: Category Id, dtype: int64

In [24]:
df['Category Name'].value_counts()

Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Water Sports            15540
Camping & Hiking        13729
Cardio Equipment        12487
Shop By Sport           10984
Electronics              3156
Accessories              1780
Golf Balls               1475
Girls' Apparel           1201
Golf Gloves              1070
Trade-In                  974
Video Games               838
Children's Clothing       652
Women's Clothing          650
Baseball & Softball       632
Hockey                    614
Cameras                   592
Toys                      529
Golf Shoes                524
Pet Supplies              492
Garden                    484
Crafts                    484
DVDs                      483
Computers                 442
Golf Apparel              441
Hunting & Shooting        440
Music                     434
Consumer Electronics      431
Boxing & MMA              423
Books                     405
Kids' Golf Clubs          384
Health and Beauty         362
Sporting Goods            357
Lacrosse                  343
Tennis & Racquet          328
Fitness Accessories       309
Men's Golf Clubs          283
CDs                       271
Men's Clothing            208
Baby                      207
Women's Golf Clubs        181
Soccer                    138
Strength Training         111
As Seen on  TV!            68
Basketball                 67
Golf Bags & Carts          61
Name: Category Name, dtype: int64

In [25]:
df['Customer City'].value_counts()

Caguas         66770
Chicago         3885
Los Angeles     3417
Brooklyn        3412
New York        1816
               ...
Bartlett          25
Malden            22
Ponce             22
Freehold          13
CA                 3
Name: Customer City, Length: 563, dtype: int64

In [26]:
df['Customer Id'].value_counts()

5654     47
10591    45
5004     45
5715     44
3708     44
         ..
18698     1
15537     1
15484     1
20681     1
2677      1
Name: Customer Id, Length: 20652, dtype: int64

In [27]:
df['Customer Segment'].value_counts()

Consumer       93504
Corporate      54789
Home Office    32226
Name: Customer Segment, dtype: int64

In [28]:
df['Customer Country'].value_counts()

EE. UU.        111146
Puerto Rico     69373
Name: Customer Country, dtype: int64

In [29]:
df['Customer State'].value_counts()

PR       69373
CA       29223
NY       11327
TX        9103
IL        7631
FL        5456
OH        4095
PA        3824
MI        3804
NJ        3191
AZ        3026
GA        2503
MD        2415
NC        1992
CO        1914
VA        1849
OR        1668
MA        1607
TN        1582
NV        1440
MO        1354
HI        1248
CT        1094
UT         968
NM         949
LA         948
WA         920
WI         850
MN         672
SC         665
IN         581
DC         579
KY         487
KS         458
DE         269
RI         243
WV         241
OK         232
ND         215
ID         167
AR         164
MT          87
IA          67
AL          35
95758        2
91732        1
Name: Customer State, dtype: int64

In [30]:
df['Department Name'].value_counts()

Fan Shop              66861
Apparel               48998
Golf                  33220
Footwear              14525
Outdoors               9686
Fitness                2479
Discs Shop             2026
Technology             1465
Pet Shop                492
Book Shop               405
Health and Beauty       362
Name: Department Name, dtype: int64

In [31]:
df['Market'].value_counts()

LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: Market, dtype: int64

In [32]:
df['Order City'].value_counts() #remove this column

Santo Domingo    2211
New York City    2202
Los Angeles      1845
Tegucigalpa      1783
Managua          1682
                 ...
Libourne            1
Bergerac            1
Juliaca             1
Takasaki            1
Pernik              1
Name: Order City, Length: 3597, dtype: int64

In [33]:
df['Order Status'].unique()

array(['COMPLETE', 'PENDING', 'CLOSED', 'PENDING_PAYMENT', 'CANCELED',
       'PROCESSING', 'SUSPECTED_FRAUD', 'ON_HOLD', 'PAYMENT_REVIEW'],
      dtype=object)

In [34]:
df['Order Country'].value_counts()

Estados Unidos       24840
Francia              13222
México               13172
Alemania              9564
Australia             8497
                     ...
Guinea Ecuatorial        2
Kuwait                   2
Sáhara Occidental        2
Burundi                  1
Serbia                   1
Name: Order Country, Length: 164, dtype: int64

In [35]:
df['order date (DateOrders)'].value_counts()

3/29/2017 23:43     5
11/23/2015 9:42     5
6/19/2017 6:26      5
6/19/2017 5:23      5
6/19/2017 2:35      5
                   ..
11/24/2017 18:08    1
11/24/2017 18:29    1
11/24/2017 18:50    1
11/24/2017 19:11    1
1/1/2015 0:00       1
Name: order date (DateOrders), Length: 65752, dtype: int64

In [36]:
df['Order Id'].value_counts()

48880    5
3605     5
28265    5
50037    5
27861    5
        ..
42011    1
42068    1
42072    1
42118    1
26118    1
Name: Order Id, Length: 65752, dtype: int64

In [37]:
df['Order Item Discount'].value_counts()

0.000000      10028
6.000000       4589
12.000000      4067
4.000000       3647
8.000000       3626
              ...
23.750000         1
96.000000         1
400.000000        1
31.980000         1
61.189999         1
Name: Order Item Discount, Length: 1017, dtype: int64

In [38]:
df['Order Item Product Price'].value_counts()

59      25027
129     22372
50      21035
49      19298
399     17392
        ...
349        40
329        27
599        21
1999       15
999        10
Name: Order Item Product Price, Length: 65, dtype: int64

In [39]:
df['Order Item Id'].value_counts()

180517    1
42681     1
28953     1
39851     1
173601    1
         ..
14991     1
150102    1
138584    1
150270    1
65113     1
Name: Order Item Id, Length: 180519, dtype: int64

In [40]:
df['Order Item Profit Ratio'].value_counts()

 0.48    9197
 0.35    7997
 0.26    6577
 0.34    6507
 0.47    6378
         ...
-2.07      18
-0.90      18
-2.30      18
-1.10      18
-2.10      18
Name: Order Item Profit Ratio, Length: 162, dtype: int64

In [41]:
df['Order Item Quantity'].value_counts()

1    99134
5    20385
3    20350
4    20335
2    20315
Name: Order Item Quantity, dtype: int64

In [42]:
df['Sales'].value_counts()

129.990005    22372
399.980011    17325
199.990005    15622
299.980011    13729
179.970001     5016
              ...
999.989990       10
379.959992       10
198.000000        9
396.000000        9
99.000000         9
Name: Sales, Length: 193, dtype: int64

In [43]:
df['Order Profit Per Order'].value_counts()

 0.000000      1177
 143.990005     199
 72.000000      194
 46.799999      188
 24.000000      181
               ...
-48.830002        1
 48.220001        1
-145.729996       1
-330.109985       1
-337.100006       1
Name: Order Profit Per Order, Length: 21998, dtype: int64

In [44]:
df['Order Region'].value_counts()

Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: Order Region, dtype: int64

In [45]:
df['Order State'].value_counts()

Inglaterra                     6722
California                     4966
Isla de Francia                4580
Renania del Norte-Westfalia    3303
San Salvador                   3055
                               ...
Kabarole                          1
Vrancea                           1
Buyumbura Mairie                  1
Aomori                            1
Iringa                            1
Name: Order State, Length: 1089, dtype: int64

In [46]:
df['Order Status'].value_counts()

COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: Order Status, dtype: int64

In [47]:
df['Product Card Id'].value_counts()

365     24515
403     22246
502     21035
1014    19298
1004    17325
        ...
127        27
208        15
860        11
226        10
60         10
Name: Product Card Id, Length: 118, dtype: int64

In [48]:
df['Product Name'].value_counts()

Perfect Fitness Perfect Rip Deck                 24515
Nike Men's CJ Elite 2 TD Football Cleat          22246
Nike Men's Dri-FIT Victory Golf Polo             21035
O'Brien Men's Neoprene Life Vest                 19298
Field & Stream Sportsman 16 Gun Fire Safe        17325
                                                 ...
Stiga Master Series ST3100 Competition Indoor       27
SOLE E35 Elliptical                                 15
Bushnell Pro X7 Jolt Slope Rangefinder              11
Bowflex SelectTech 1090 Dumbbells                   10
SOLE E25 Elliptical                                 10
Name: Product Name, Length: 118, dtype: int64

In [49]:
df['shipping date (DateOrders)'].value_counts()

9/16/2015 16:27    10
9/23/2016 21:01    10
1/5/2016 5:58      10
2/11/2017 3:28     10
6/2/2017 9:27      10
                   ..
2/28/2016 23:50     1
6/2/2015 20:48      1
12/1/2017 23:55     1
6/2/2015 20:32      1
12/23/2015 1:25     1
Name: shipping date (DateOrders), Length: 63701, dtype: int64

In [50]:
df['Shipping Mode'].value_counts()

Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: Shipping Mode, dtype: int64

In [51]:
df['Order Status'].unique()

array(['COMPLETE', 'PENDING', 'CLOSED', 'PENDING_PAYMENT', 'CANCELED',
       'PROCESSING', 'SUSPECTED_FRAUD', 'ON_HOLD', 'PAYMENT_REVIEW'],
      dtype=object)

### Converting float values into integers for better understanding

In [52]:
#Sales per customer:-
df['Sales per customer']=df['Sales per customer'].astype(int)
df['Sales per customer'].dtypes

dtype('int32')

## Correlation of the features

In [53]:
df.corr()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
Days for shipping (real),1.000000,0.515880,-0.005101,0.001758,0.401415,-0.000348,0.003432,0.000112,-0.001631,-0.004073,...,-0.000811,0.001962,0.001757,-0.005101,-0.000811,-0.000859,-0.000348,NaN,0.002185,NaN
Days for shipment (scheduled),0.515880,1.000000,-0.000185,0.006452,-0.369352,-0.000367,0.000899,-0.003019,-0.000262,-0.005300,...,-0.002925,0.006327,0.006445,-0.000185,0.005249,-0.000431,-0.000367,NaN,0.006912,NaN
Benefit per order,-0.005101,-0.000185,1.000000,0.133488,-0.003727,0.031889,0.009354,0.002235,0.031442,0.000338,...,0.015696,0.131816,0.133484,1.000000,-0.004978,0.033161,0.031889,NaN,0.103459,NaN
Sales per customer,0.001758,0.006452,0.133488,1.000000,-0.003801,0.224795,0.060415,-0.001307,0.231961,-0.000222,...,0.105930,0.989714,0.999996,0.133488,-0.000149,0.235864,0.224795,NaN,0.781529,NaN
Late_delivery_risk,0.401415,-0.369352,-0.003727,-0.003801,1.000000,0.001752,0.001484,0.003148,0.001077,0.000679,...,-0.000139,-0.003564,-0.003791,-0.003727,-0.014131,0.001490,0.001752,NaN,-0.002175,NaN
Category Id,-0.000348,-0.000367,0.031889,0.224795,0.001752,1.000000,0.274633,0.002898,0.888835,0.002195,...,-0.302408,0.227483,0.225201,0.031889,-0.005943,0.991092,1.000000,NaN,0.461059,NaN
Customer Id,0.003432,0.000899,0.009354,0.060415,0.001484,0.274633,1.000000,0.002022,0.136897,0.002335,...,-0.091328,0.060961,0.060181,0.009354,-0.005659,0.228039,0.274633,NaN,0.111118,NaN
Customer Zipcode,0.000112,-0.003019,0.002235,-0.001307,0.003148,0.002898,0.002022,1.000000,0.002878,0.584553,...,-0.006174,-0.001490,-0.001304,0.002235,0.011843,0.003173,0.002898,NaN,0.002191,NaN
Department Id,-0.001631,-0.000262,0.031442,0.231961,0.001077,0.888835,0.136897,0.002878,1.000000,0.002460,...,-0.265437,0.234718,0.232367,0.031442,-0.005982,0.906117,0.888835,NaN,0.446743,NaN
Latitude,-0.004073,-0.005300,0.000338,-0.000222,0.000679,0.002195,0.002335,0.584553,0.002460,1.000000,...,-0.001853,-0.000696,-0.000223,0.000338,-0.002921,0.002031,0.002195,NaN,0.000471,NaN
Longitude,0.003911,0.003675,-0.002521,0.001448,-0.001915,-0.002320,-0.005146,-0.923921,-0.002435,-0.525122,...,0.004467,0.001696,0.001444,-0.002521,-0.005880,-0.002580,-0.002320,NaN,-0.000894,NaN
Order Customer Id,0.003432,0.000899,0.009354,0.060415,0.001484,0.274633,1.000000,0.002022,0.136897,0.002335,...,-0.091328,0.060961,0.060181,0.009354,-0.005659,0.228039,0.274633,NaN,0.111118,NaN
Order Id,-0.001711,-0.001878,0.013716,0.079187,-0.001293,0.198496,0.204821,-0.001210,0.106757,-0.002984,...,-0.087073,0.079835,0.079000,0.013716,0.013971,0.163416,0.198496,NaN,0.115324,NaN
Order Item Cardprod Id,-0.000859,-0.000431,0.033161,0.235864,0.001490,0.991092,0.228039,0.003173,0.906117,0.002031,...,-0.312555,0.238789,0.236367,0.033161,-0.005658,1.000000,0.991092,NaN,0.480288,NaN
Order Item Discount,0.002231,0.002897,0.064756,0.498575,-0.000750,0.140180,0.038490,-0.001861,0.144617,-0.002997,...,0.065379,0.617438,0.498734,0.064756,0.003921,0.147294,0.140180,NaN,0.488101,NaN
Order Item Discount Rate,0.001467,0.000065,-0.018644,-0.119659,0.000404,0.000572,0.001712,-0.000135,0.000255,-0.003889,...,-0.000028,0.000346,-0.119469,-0.018644,0.002691,0.000731,0.000572,NaN,0.000345,NaN
Order Item Id,-0.001769,-0.001848,0.013556,0.078356,-0.001376,0.186796,0.191814,-0.001208,0.101676,-0.003058,...,-0.083643,0.079002,0.078176,0.013556,0.013867,0.154077,0.186796,NaN,0.112448,NaN
Order Item Product Price,0.002178,0.006909,0.103473,0.781603,-0.002179,0.461128,0.111432,0.002192,0.446870,0.000476,...,-0.475978,0.790019,0.781851,0.103473,-0.000142,0.480265,0.461128,NaN,0.999997,NaN
Order Item Profit Ratio,-0.004638,-0.001822,0.823689,-0.001435,-0.002316,-0.001614,-0.000337,0.003364,-0.003044,-0.000081,...,0.001128,-0.001766,-0.001439,0.823689,-0.005650,-0.001784,-0.001614,NaN,-0.002043,NaN
Order Item Quantity,-0.000811,-0.002925,0.015696,0.105930,-0.000139,-0.302408,-0.091328,-0.006174,-0.265437,-0.001853,...,1.000000,0.106442,0.105413,0.015696,0.001662,-0.312555,-0.302408,NaN,-0.476232,NaN
Sales,0.001962,0.006327,0.131816,0.989714,-0.003564,0.227483,0.060961,-0.001490,0.234718,-0.000696,...,0.106442,1.000000,0.989744,0.131816,0.000564,0.238789,0.227483,NaN,0.789948,NaN
Order Item Total,0.001757,0.006445,0.133484,0.999996,-0.003791,0.225201,0.060181,-0.001304,0.232367,-0.000223,...,0.105413,0.989744,1.000000,0.133484,-0.000138,0.236367,0.225201,NaN,0.781781,NaN
Order Profit Per Order,-0.005101,-0.000185,1.000000,0.133488,-0.003727,0.031889,0.009354,0.002235,0.031442,0.000338,...,0.015696,0.131816,0.133484,1.000000,-0.004978,0.033161,0.031889,NaN,0.103459,NaN
Order Zipcode,-0.000811,0.005249,-0.004978,-0.000149,-0.014131,-0.005943,-0.005659,0.011843,-0.005982,-0.002921,...,0.001662,0.000564,-0.000138,-0.004978,1.000000,-0.005658,-0.005943,NaN,-0.000121,NaN
Product Card Id,-0.000859,-0.000431,0.033161,0.235864,0.001490,0.991092,0.228039,0.003173,0.906117,0.002031,...,-0.312555,0.238789,0.236367,0.033161,-0.005658,1.000000,0.991092,NaN,0.480288,NaN
Product Category Id,-0.000348,-0.000367,0.031889,0.224795,0.001752,1.000000,0.274633,0.002898,0.888835,0.002195,...,-0.302408,0.227483,0.225201,0.031889,-0.005943,0.991092,1.000000,NaN,0.461059,NaN
Product Description,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Price,0.002185,0.006912,0.103459,0.781529,-0.002175,0.461059,0.111118,0.002191,0.446743,0.000471,...,-0.476232,0.789948,0.781781,0.103459,-0.000121,0.480288,0.461059,NaN,1.000000,NaN
Product Status,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Data Cleaning and Feature Engineering

In [54]:
#combining customer first name and last name.

df['CustomerFullName'] = df['Customer Fname'] + ' ' + df['Customer Lname']

In [55]:
dropped_col=['Days for shipping (real)','Order Item Total','Benefit per order','Days for shipment (scheduled)','Customer Fname','Customer Lname','Latitude','Longitude','Product Description','Customer Zipcode','Customer Street','Customer Email','Customer Password','Order Zipcode','Department Id','Order Customer Id','Order Item Discount Rate','Order Item Cardprod Id','Product Image','Product Category Id','Product Status','Product Price','Product Card Id']
df.drop(dropped_col,axis=1,inplace=True)

In [56]:
df['order date (DateOrders)'] = df['order date (DateOrders)'].astype(str).str.split().str[0]
df['shipping date (DateOrders)'] = df['shipping date (DateOrders)'].astype(str).str.split().str[0]

In [57]:
#Converting the data type into date time
df['order date (DateOrders)']= pd.to_datetime(df['order date (DateOrders)'])
df['order date (DateOrders)']

0        2018-01-31
1        2018-01-13
2        2018-01-13
3        2018-01-13
4        2018-01-13
            ...
180514   2016-01-16
180515   2016-01-16
180516   2016-01-15
180517   2016-01-15
180518   2016-01-15
Name: order date (DateOrders), Length: 180519, dtype: datetime64[ns]

In [58]:
#Converting the data type into date time
df['shipping date (DateOrders)']= pd.to_datetime(df['shipping date (DateOrders)'])
df['shipping date (DateOrders)']

0        2018-02-03
1        2018-01-18
2        2018-01-17
3        2018-01-16
4        2018-01-15
            ...
180514   2016-01-20
180515   2016-01-19
180516   2016-01-20
180517   2016-01-18
180518   2016-01-19
Name: shipping date (DateOrders), Length: 180519, dtype: datetime64[ns]

In [59]:
# Create a new column to calculate the delay in days for each shipment
df['Delay'] = (pd.to_datetime(df['shipping date (DateOrders)']) - pd.to_datetime(df['order date (DateOrders)'])).dt.days

**Sales**

In [60]:
df['Sales'].unique()

array([ 327.75      ,  119.9800034 ,   79.98000336,  100.        ,
         89.98000336,  109.9400024 ,  299.9700012 ,  119.9700012 ,
         65.97000122,   95.97000122,  179.9700012 ,  150.        ,
        250.        ,  199.9499969 ,  239.9499969 ,  159.9499969 ,
        449.9500122 ,  149.9499969 ,  299.9500122 ,  499.9500122 ,
         99.98999786,  129.9900055 ,   59.99000168,  299.980011  ,
        252.8800049 ,  452.0400085 , 1500.        ,  999.9899902 ,
         79.98999786,   44.99000168,  134.9700012 ,   75.        ,
         74.97000122,   47.97000122,  239.9600067 ,  200.        ,
        159.9600067 ,   99.95999908,  399.9599915 ,  120.        ,
        215.8200073 ,  461.480011  ,  210.8500061 ,  124.9499969 ,
         79.94999695,  224.9499969 ,  174.9499969 ,  139.9499969 ,
        140.        ,   50.        ,   63.97999954,   49.97999954,
         39.97999954,   95.98000336,  127.9599991 ,  207.9600067 ,
        350.        ,   99.94999695,  399.9899902 ,   27.98999977,
        299.9899902 ,  357.1000061 ,  125.        ,   79.95999908,
        179.9600067 ,  280.        ,   59.08000183,   31.97999954,
        199.9799957 ,   55.97999954,   60.        ,   31.98999977,
         24.98999977,  199.        ,  399.980011  ,   31.07999992,
         89.98999786,   39.99000168,   30.        ,   19.98999977,
        109.9499969 ,  164.3800049 ,   11.28999996,   63.95999908,
        191.9600067 ,  319.9599915 ,  111.9599991 ,  139.9600067 ,
        379.9599915 ,   89.94999695,  259.9500122 ,  495.        ,
         21.98999977,  532.5800171 ,   47.99000168,   15.98999977,
         51.99000168,  103.9800034 ,   43.97999954,   69.98000336,
         90.        ,  104.9700012 ,   44.        ,   88.        ,
         22.        ,   66.        ,  110.        ,   25.        ,
         70.        ,  149.9900055 ,   34.99000168,  199.9900055 ,
         17.98999977,   84.40000153,  293.0400085 ,  249.9900055 ,
        260.6499939 ,  155.9700012 ,  274.8500061 ,   39.75      ,
         29.98999977,  399.9500122 ,   71.95999908,  219.8800049 ,
        299.8500061 ,  164.9100037 ,   59.97000122,  143.9700012 ,
        210.        ,   83.97000122,   53.97000122,  329.9899902 ,
        159.9900055 ,  599.9899902 ,   54.97000122,   59.97999954,
        199.8999939 ,  284.9700012 ,   89.97000122,  119.9599991 ,
         87.95999908,  159.9799957 ,   35.97999954,  297.        ,
        399.7999878 ,  189.9799957 ,  179.9799957 ,  189.        ,
        359.9599915 ,  499.75      ,  474.9500122 ,  239.9700012 ,
        124.9899979 , 1999.98999   ,  198.        ,  269.9700012 ,
        396.        ,   99.        ,   94.98999786,   14.98999977,
         29.97999954,   59.95999908,   44.97000122,   74.94999695,
        179.9900055 ,   39.95999908,   29.96999931,   19.97999954,
          9.98999977,   49.95000076,  169.9900055 ,  160.        ,
         80.        ,  320.        ,  400.        ,  240.        ,
        325.        ,   65.        ,  130.        ,  195.        ,
        260.        ,  108.        ,  300.        ,  500.        ,
        119.9899979 ,  209.9900055 ,  109.9899979 ,  134.9900055 ,
         11.53999996,  349.9899902 ,  149.9400024 ,  249.8999939 ,
        199.9199982 ])

In [61]:
Sales_range = [0, 500, 1000, 1500, 2000]
Sales_labels = ['<500', '500-1000', '1000-1500', '1500-2000']

# Assign salary brackets to dataset
df['Sales Range'] = pd.cut(df['Sales'], bins=Sales_range, labels=Sales_labels)

# View the updated dataset
print(df.head())

       Type  Sales per customer   Delivery Status  Late_delivery_risk  \
0     DEBIT                 314  Advance shipping                   0
1  TRANSFER                 311     Late delivery                   1
2      CASH                 309  Shipping on time                   0
3     DEBIT                 304  Advance shipping                   0
4   PAYMENT                 298  Advance shipping                   0

   Category Id   Category Name Customer City Customer Country  Customer Id  \
0           73  Sporting Goods        Caguas      Puerto Rico        20755
1           73  Sporting Goods        Caguas      Puerto Rico        19492
2           73  Sporting Goods      San Jose          EE. UU.        19491
3           73  Sporting Goods   Los Angeles          EE. UU.        19490
4           73  Sporting Goods        Caguas      Puerto Rico        19489

  Customer Segment  ... Order Profit Per Order    Order Region  \
0         Consumer  ...              91.250000  Southeast Asia
1         Consumer  ...            -249.089996      South Asia
2         Consumer  ...            -247.779999      South Asia
3      Home Office  ...              22.860001         Oceania
4        Corporate  ...             134.210007         Oceania

       Order State     Order Status  Product Name shipping date (DateOrders)  \
0  Java Occidental         COMPLETE  Smart watch                  2018-02-03
1         Rajastán          PENDING  Smart watch                  2018-01-18
2         Rajastán           CLOSED  Smart watch                  2018-01-17
3       Queensland         COMPLETE  Smart watch                  2018-01-16
4       Queensland  PENDING_PAYMENT  Smart watch                  2018-01-15

    Shipping Mode   CustomerFullName  Delay  Sales Range
0  Standard Class     Cally Holloway      3         <500
1  Standard Class         Irene Luna      5         <500
2  Standard Class  Gillian Maldonado      4         <500
3  Standard Class          Tana Tate      3         <500
4  Standard Class     Orli Hendricks      2         <500

[5 rows x 33 columns]

In [62]:
df.duplicated().sum()

0

In [63]:
df.columns

Index(['Type', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk',
       'Category Id', 'Category Name', 'Customer City', 'Customer Country',
       'Customer Id', 'Customer Segment', 'Customer State', 'Department Name',
       'Market', 'Order City', 'Order Country', 'order date (DateOrders)',
       'Order Id', 'Order Item Discount', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Profit Per Order',
       'Order Region', 'Order State', 'Order Status', 'Product Name',
       'shipping date (DateOrders)', 'Shipping Mode', 'CustomerFullName',
       'Delay', 'Sales Range'],
      dtype='object')

## Exporting the Cleaned Dataset as CSV for next steps

In [64]:
df.dtypes

Type                                  object
Sales per customer                     int32
Delivery Status                       object
Late_delivery_risk                     int64
Category Id                            int64
Category Name                         object
Customer City                         object
Customer Country                      object
Customer Id                            int64
Customer Segment                      object
Customer State                        object
Department Name                       object
Market                                object
Order City                            object
Order Country                         object
order date (DateOrders)       datetime64[ns]
Order Id                               int64
Order Item Discount                  float64
Order Item Id                          int64
Order Item Product Price               int64
Order Item Profit Ratio              float64
Order Item Quantity                    int64
Sales                                float64
Order Profit Per Order               float64
Order Region                          object
Order State                           object
Order Status                          object
Product Name                          object
shipping date (DateOrders)    datetime64[ns]
Shipping Mode                         object
CustomerFullName                      object
Delay                                  int64
Sales Range                         category
dtype: object

In [65]:
df.shape

(180519, 33)

In [66]:
df.corr()

,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Order Id,Order Item Discount,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Profit Per Order,Delay
Sales per customer,1.000000,-0.003801,0.224795,0.060415,0.079187,0.498575,0.078356,0.781603,-0.001435,0.105930,0.989714,0.133488,0.001758
Late_delivery_risk,-0.003801,1.000000,0.001752,0.001484,-0.001293,-0.000750,-0.001376,-0.002179,-0.002316,-0.000139,-0.003564,-0.003727,0.401415
Category Id,0.224795,0.001752,1.000000,0.274633,0.198496,0.140180,0.186796,0.461128,-0.001614,-0.302408,0.227483,0.031889,-0.000348
Customer Id,0.060415,0.001484,0.274633,1.000000,0.204821,0.038490,0.191814,0.111432,-0.000337,-0.091328,0.060961,0.009354,0.003432
Order Id,0.079187,-0.001293,0.198496,0.204821,1.000000,0.049385,0.999623,0.115582,0.002760,-0.087073,0.079835,0.013716,-0.001711
Order Item Discount,0.498575,-0.000750,0.140180,0.038490,0.049385,1.000000,0.048866,0.488146,-0.002788,0.065379,0.617438,0.064756,0.002231
Order Item Id,0.078356,-0.001376,0.186796,0.191814,0.999623,0.048866,1.000000,0.112696,0.002785,-0.083643,0.079002,0.013556,-0.001769
Order Item Product Price,0.781603,-0.002179,0.461128,0.111432,0.115582,0.488146,0.112696,1.000000,-0.002042,-0.475978,0.790019,0.103473,0.002178
Order Item Profit Ratio,-0.001435,-0.002316,-0.001614,-0.000337,0.002760,-0.002788,0.002785,-0.002042,1.000000,0.001128,-0.001766,0.823689,-0.004638
Order Item Quantity,0.105930,-0.000139,-0.302408,-0.091328,-0.087073,0.065379,-0.083643,-0.475978,0.001128,1.000000,0.106442,0.015696,-0.000811
Sales,0.989714,-0.003564,0.227483,0.060961,0.079835,0.617438,0.079002,0.790019,-0.001766,0.106442,1.000000,0.131816,0.001962
Order Profit Per Order,0.133488,-0.003727,0.031889,0.009354,0.013716,0.064756,0.013556,0.103473,0.823689,0.015696,0.131816,1.000000,-0.005101
Delay,0.001758,0.401415,-0.000348,0.003432,-0.001711,0.002231,-0.001769,0.002178,-0.004638,-0.000811,0.001962,-0.005101,1.000000

In [67]:
# saving the dataframe to csv 
df.to_csv('Cleaned_DataCoSupplyChainDataset.csv',index=False)

In [68]:
# Read saved file and display  top 5 rows 
df_new = pd.read_csv('Cleaned_DataCoSupplyChainDataset.csv')
df_new.head(n=5)

,Type,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Id,Customer Segment,...,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,shipping date (DateOrders),Shipping Mode,CustomerFullName,Delay,Sales Range
0,DEBIT,314,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,20755,Consumer,...,91.250000,Southeast Asia,Java Occidental,COMPLETE,Smart watch,2018-02-03,Standard Class,Cally Holloway,3,<500
1,TRANSFER,311,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,19492,Consumer,...,-249.089996,South Asia,Rajastán,PENDING,Smart watch,2018-01-18,Standard Class,Irene Luna,5,<500
2,CASH,309,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,19491,Consumer,...,-247.779999,South Asia,Rajastán,CLOSED,Smart watch,2018-01-17,Standard Class,Gillian Maldonado,4,<500
3,DEBIT,304,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,19490,Home Office,...,22.860001,Oceania,Queensland,COMPLETE,Smart watch,2018-01-16,Standard Class,Tana Tate,3,<500
4,PAYMENT,298,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,19489,Corporate,...,134.210007,Oceania,Queensland,PENDING_PAYMENT,Smart watch,2018-01-15,Standard Class,Orli Hendricks,2,<500